definitions:
  controllers.signUpResult:
    properties:
      InsertedID:
        type: string
    type: object
  controllers.userSignUp:
    properties:
      email:
        type: string
      first_name:
        maxLength: 100
        minLength: 1
        type: string
      last_name:
        maxLength: 100
        minLength: 1
        type: string
      password:
        type: string
    required:
    - first_name
    - last_name
    type: object
info:
  contact: {}
  title: SPLAT Service
paths:
  /users/signup:
    post:
      description: Responds with userId
      parameters:
      - description: sign up data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/controllers.userSignUp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.signUpResult'
        "400":
          description: Bad Request
      summary: User sign up
swagger: "2.0"
